<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

| Term       | Brief Description                                                         |
|------------|:-------------------------------------------------------------------------:|
| Subsetting | Forming of smaller sets using certain elements from a larger defined set  |
| Indexing   | Calling of single elements from a complete set                            |
| Slicing    | _Refers to getting a range of elements_                                   |
| Masking    | Identifying elements that satisfy specific criteria to form a smaller set |

In [2]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
#Use masking to subset the letters that correspond to the odd numbers.
npArrayNumbers = np_array_2d[0:10, 0]
print(npArrayNumbers)
npArrayNumbers = npArrayNumbers.astype(int)
oddMask = npArrayNumbers%2 == 1
print(oddMask)
npArrayLetters = np_array_2d[oddMask, 1]
print(npArrayLetters)

['1' '3' '2' '4' '5' '7' '6' '8' '10' '9']
[ True  True False False  True  True False False False  True]
['A' 'C' 'E' 'G' 'I']


In [37]:
coolArray = np.array([[66, 50, 57, -1, -1],
                      [92, -1, 88, -1, -1],
                      [75, -1, -1, 76, -1],
                      [-1, 51, 87, -1, -1],
                      [71, -1, 67, -1, 69]])

greaterThanFifty = coolArray > 50
print(greaterThanFifty)
lessThanFifty = coolArray < 50
exactlyFifty = coolArray == 50

coolArray[greaterThanFifty] = 1
coolArray[lessThanFifty] = -1
coolArray[exactlyFifty] = 0
print(coolArray)

[[ True False  True False False]
 [ True False  True False False]
 [ True False False  True False]
 [False  True  True False False]
 [ True False  True False  True]]
[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]


In [9]:
coolArray = np.array([[66, 50, 57, -1, -1],
                      [92, -1, 88, -1, -1],
                      [75, -1, -1, 76, -1],
                      [-1, 51, 87, -1, -1],
                      [71, -1, 67, -1, 69]])

coolArray2 = coolArray.copy()

coolArray2[coolArray > 50] = 1
coolArray2[coolArray < 50] = -1
coolArray2[coolArray == 50] = 0
print(coolArray)
print(coolArray2)

[[66 50 57 -1 -1]
 [92 -1 88 -1 -1]
 [75 -1 -1 76 -1]
 [-1 51 87 -1 -1]
 [71 -1 67 -1 69]]
[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]


In [1]:
hannah = ['h','a','n','n','a','h']
nus = ['n', 'u', 's']
print(nus[::-1])
print(hannah[::-1])

['s', 'u', 'n']
['h', 'a', 'n', 'n', 'a', 'h']


In [27]:
hannah2 = ['a','b','c','d','e','f']
for i in range(len(hannah2)):
    print(hannah2[5:i:-1])

print(hannah2[::-1])

['f', 'e', 'd', 'c', 'b']
['f', 'e', 'd', 'c']
['f', 'e', 'd']
['f', 'e']
['f']
[]
['f', 'e', 'd', 'c', 'b', 'a']


# 