<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

# 1 Lists, Arrays & Dictionaries

In [ ]:
import numpy as np
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [ ]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

In [ ]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

## 1.1 Let’s compare

In [6]:
fruits = ["apple", "orange", "pear", "durian"]
fruits[-1]

'durian'

In [9]:
fruits[3] = "banana"

In [10]:
fruits[3]

'banana'

## 1.2 Accessing data from a list (or array)

In [11]:
vegetables = {
    "banana": "broccoli",
    "apple": "spinach",
    "orange": "egg"
}
vegetables["banana"]

'broccoli'

In [12]:
vegetables.keys()

dict_keys(['banana', 'apple', 'orange'])

In [13]:
vegetables.values()

dict_values(['broccoli', 'spinach', 'egg'])

## 1.3 Accessing data from a dictionary

## 1.4 Higher dimensional lists

In [14]:
vegetables["broccoli"]

KeyError: 'broccoli'

# 2 Lists vs. Arrays

## 2.1 Size

In [24]:
import numpy as np
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array
len(py_list_2d)
len(np_array_2d)
np_array_2d.shape
np_array_2d

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C'],
       ['4', 'D'],
       ['5', 'E'],
       ['6', 'F'],
       ['7', 'G'],
       ['8', 'H'],
       ['9', 'I'],
       ['10', 'J']], dtype='<U21')

In [19]:
len(py_list_2d)

10

In [20]:
len(np_array_2d)

10

## 2.2 Arrays are fussy about type

In [21]:
py_list = [1, 1.5, "A"]
np_array = np.array(py_list)

In [23]:
py_list
np_array

array(['1', '1.5', 'A'], dtype='<U32')

## 2.3 Adding a number

In [25]:
pyList = [1, 2, 3, 4, 5]
npArray = np.array(pyList)

npArray + 10

array([11, 12, 13, 14, 15])

## 2.4 Adding another list

In [29]:
pyList1 = [1, 2, 3, 4, 5]
pyList2 = [10, 20, 30, 40, 50]

npArray1 = np.array(pyList1)
npArray2 = np.array(pyList2)

pyList1 + pyList2
npArray1 + npArray2

array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a Number

## 2.6 Squaring

## 2.7 Asking questions

In [30]:
pyList = [1, 2, 3, 4, 5]
npArray = np.array(pyList)

pyList == 3

False

In [31]:
npArray == 3

array([False, False,  True, False, False])

In [32]:
npArray > 3

array([False, False, False,  True,  True])

## 2.8 Mathematics

In [33]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)    

sum(py_list)     # sum() is a base Python function
max(py_list)     # max() is a base Python function
min(py_list)     # min() is a base Python function
np_array.sum()
np_array.max()
np_array.min()
np_array.mean()
np_array.std()

np.float64(1.4142135623730951)

In [35]:
sum(np_array)

np.int64(15)

In [37]:
np_array.sum()

np.int64(15)

## Footnotes